### ISSUE TITLE
Standard Protocols for Connectivity

### ISSUE THREAD

**Issue by benhylau** [benhylau/wrbt#2]
We need a standard way for Alice to, in her peering request, indicate to Bob how her node would like to peer with other nodes. I am wondering if by specifying the **interface** and **link**, Bob will be able to figure out whether his node can peer with Alice's, and unambiguously create a set of credentials for her.

I am not sure if these are reasonable groupings, and whether they reflect the protocols currently supported by cjdns. Would definitely like some feedback.
### Interfaces

| Interface | Support |
| :-- | :-- |
| UDP | IPv4 or IPv6 |
| ETH | All beacon modes |
### Physical Links

| Link | Via | UDP | ETH |
| :-- | :-- | :-: | :-: |
| WiFi Direct | Connected devices | :heavy_check_mark: | :heavy_check_mark: |
| Bluetooth | Paired devices | :heavy_check_mark: | :heavy_check_mark: |
| Clearnet Overlay | WiFi AP or mobile network | :heavy_check_mark: |  |

*_Android nodes will not support peering over ETH at the moment_

**Comment by kpcyrd** [comment]
Ethernet peering is usually unauthenticated, so we don't need a credential exchange for that :)

The password is authenticated for all transports.

**Comment by benhylau** [comment]
@kpcyrd Updated in https://github.com/benhylau/wrbt/pull/4 and merged to [master](https://github.com/benhylau/wrbt). See section on Unauthenticated Connections.
